import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.less';
import { Button, Pagination, Steps } from 'antd';
import DatePicker from '../components/Datepicker';

const { Step } = Steps;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <DatePicker />
        <Button type='primary'>Anjoi</Button>
        <Pagination defaultCurrent={1} total={50} />
      </main>
      <Steps current={1}>
        <Step title='Finished' description='This is a description.' />
        <Step
          title='In Progress'
          subTitle='Left 00:00:08'
          description='This is a description.'
        />
        <Step title='Waiting' description='This is a description.' />
      </Steps>
      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
